name: "Nette Tester"

on:
  pull_request:
  workflow_dispatch:

  push:
    branches: [ "**" ]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  test84:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/phpunit.yml@master
    with:
      php: "8.4"
      make: "init tests"

  test85:
    name: "Tester"
    uses: contributte/.github/.github/workflows/phpunit.yml@master
    with:
      php: "8.5"
      make: "init tests"

  testlower:
    name: "Tester"
    uses: contributte/.github/.github/workflows/phpunit.yml@master
    with:
      php: "8.4"
      make: "init tests"
      composer: "composer update --no-interaction --no-progress --prefer-dist --prefer-stable --prefer-lowest"
